/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : IntFlashLdd1.c
**     Project     : KESCProjectMCUXpresso
**     Processor   : SKEAZN64MLH2
**     Component   : FLASH_LDD
**     Version     : Component 01.106, Driver 01.01, CPU db: 3.00.000
**     Repository  : Kinetis
**     Compiler    : GNU C Compiler
**     Date/Time   : 2019-12-26, 16:23, # CodeGen: 53
**     Abstract    :
**          This embedded component implements an access to an on-chip flash memory.
**          Using this component the flash memory could be written to, erased,
**          read from. Some other services would be provided, if they are supported
**          by hardware, e.g. changes of the flash memory protection state.
**     Settings    :
**          Component name                                 : IntFlashLdd1
**          Device                                         : FTMRH
**          Clock frequency                                : 1 MHz
**          Use user memory areas                          : no
**          Interrupt service                              : Enabled
**            Read batch size                              : Unlimited
**            Command complete interrupt                   : 
**              Interrupt                                  : INT_FTMRH
**              Interrupt priority                         : medium priority
**          Safe launch and wait                           : yes
**            Safe routine location                        : On stack
**            Interruptable wait loop                      : no
**          Initialization                                 : 
**            Enabled in init. code                        : yes
**            Auto initialization                          : no
**            Event mask                                   : 
**              OnOperationComplete                        : Enabled
**              OnError                                    : Enabled
**            CPU clock/configuration selection            : 
**              Clock configuration 0                      : This component enabled
**              Clock configuration 1                      : This component disabled
**              Clock configuration 2                      : This component disabled
**              Clock configuration 3                      : This component disabled
**              Clock configuration 4                      : This component disabled
**              Clock configuration 5                      : This component disabled
**              Clock configuration 6                      : This component disabled
**              Clock configuration 7                      : This component disabled
**     Contents    :
**         Init               - LDD_TDeviceData* IntFlashLdd1_Init(LDD_TUserData *UserDataPtr);
**         Write              - LDD_TError IntFlashLdd1_Write(LDD_TDeviceData *DeviceDataPtr, LDD_TData...
**         GetOperationStatus - LDD_FLASH_TOperationStatus IntFlashLdd1_GetOperationStatus(LDD_TDeviceData...
**         GetError           - void IntFlashLdd1_GetError(LDD_TDeviceData *DeviceDataPtr,...
**         GetDriverState     - LDD_TDriverState IntFlashLdd1_GetDriverState(LDD_TDeviceData *DeviceDataPtr);
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file IntFlashLdd1.c
** @version 01.01
** @brief
**          This embedded component implements an access to an on-chip flash memory.
**          Using this component the flash memory could be written to, erased,
**          read from. Some other services would be provided, if they are supported
**          by hardware, e.g. changes of the flash memory protection state.
*/         
/*!
**  @addtogroup IntFlashLdd1_module IntFlashLdd1 module documentation
**  @{
*/         

/* MODULE IntFlashLdd1. */

#include "IFsh1.h"
#include "IntFlashLdd1.h"
/* {Default RTOS Adapter} No RTOS includes */
#include "SIM_PDD.h"
#include "FTMRH_PDD.h"

#ifdef __cplusplus
extern "C" {
#endif

#define SAFE_ROUTINE_SIZE 28U

/*
Safe launch and wait routine code. This code launch a command and
waits until command completion or command violation. Routine is
written as array of bytes to be constant size and compiler independent.
C language implementation could look like:

void SafeRoutine(void) {
  FTMRH_PDD_LaunchCommand(FTMRH_BASE_PTR);
  while (!FTMRH_PDD_GetCommandCompleteInterruptFlag(FTMRH_BASE_PTR)) {};
}
*/

typedef void (* LDD_FLASH_TSafeRoutinePtr)(void); /* Safe routine pointer type */

typedef struct {
  uint8_t SafeRoutine[SAFE_ROUTINE_SIZE]; /* Safe routine buffer */
} LDD_FLASH_TSafeRoutine;              /* Safe routine buffer type */

static const uint8_t SafeRoutine[SAFE_ROUTINE_SIZE - 4U] = {
  0x00U,0xb5U,               /*  push	{lr}                                         */
  0x04U,0x4aU,               /*  ldr	r2, [pc, #16]	; (bc <SafeRoutine___+0x14>) */
  0x80U,0x23U,               /*  movs	r3, #128	; 0x80                       */
  0x13U,0x70U,               /*  strb	r3, [r2, #0]                                 */
  0x11U,0x78U,               /*  ldrb	r1, [r2, #0]                                 */
  0x48U,0xb2U,               /*  sxtb	r0, r1                                       */
  0x00U,0x28U,               /*  cmp	r0, #0                                       */
  0xfbU,0xdaU,               /*  bge.n	b0 <SafeRoutine___+0x8>                      */
  0x00U,0xbdU,               /*  pop	{pc}                                         */
  0xc0U,0x46U,               /*  nop			; (mov r8, r8)               */
  (uint8_t)((0x40020006U>>0)&0xFFU),  /* FTMRH_FSTAT register address                 */
  (uint8_t)((0x40020006U>>8)&0xFFU),
  (uint8_t)((0x40020006U>>16)&0xFFU),
  (uint8_t)((0x40020006U>>24)&0xFFU)
};

typedef struct {
  LDD_FLASH_TOperationType   CurrentOperation;   /* Current operation type */
  LDD_FLASH_TOperationStatus CurrentOperationStatus; /* Current operation status */
  LDD_FLASH_TAddress         CurrentFlashAddress; /* Address of destination/source in the flash memory for the operation step */
  uint32_t                   CurrentUserAddress; /* Address of destination/source in the user memory for the operation step */
  LDD_FLASH_TDataSize        CurrentDataSize;    /* Data size of the current operation step */
  LDD_FLASH_TErrorFlags      CurrentErrorFlags;  /* Current error flags */
  LDD_TUserData             *UserDataPtr;        /* Device mode user device data structure */
} IntFlashLdd1_TDeviceData, *IntFlashLdd1_TDeviceDataPtr; /* Device data structure type */

/* {Default RTOS Adapter} Static object used for simulation of dynamic driver memory allocation */
static IntFlashLdd1_TDeviceData DevDataPtr__DEFAULT_RTOS_ALLOC;
/* {Default RTOS Adapter} Global variable used for passing a parameter into ISR */
static IntFlashLdd1_TDeviceDataPtr INT_FTMRH__DEFAULT_RTOS_ISRPARAM;

/* Internal method prototypes */
static LDD_TError CheckStateAndRange(IntFlashLdd1_TDeviceDataPtr DevDataPtr, LDD_FLASH_TAddress Address, LDD_FLASH_TDataSize Size);

/*
** ===================================================================
**     Method      :  CheckStateAndRange (component FLASH_LDD)
**
**     Description :
**         Range check internal routine. This routine is used by the 
**         component's method to test the input address range.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static LDD_TError CheckStateAndRange(IntFlashLdd1_TDeviceDataPtr DevDataPtr, LDD_FLASH_TAddress Address, LDD_FLASH_TDataSize Size)
{
  /* Input parameter test - this test can be disabled by setting the "Ignore range checking"
     property to the "yes" value in the "Configuration inspector" */
  if (Address >= (IntFlashLdd1_BLOCK0_ADDRESS + IntFlashLdd1_BLOCK0_SIZE)) {
    if (!((Address >= IntFlashLdd1_BLOCK1_ADDRESS) && ((Address < (IntFlashLdd1_BLOCK1_ADDRESS + IntFlashLdd1_BLOCK1_SIZE))))) {
      return ERR_PARAM_ADDRESS;
    }
  }
  Address += Size;
  if (Address > (IntFlashLdd1_BLOCK0_ADDRESS + IntFlashLdd1_BLOCK0_SIZE)) {
    if (!((Address >= IntFlashLdd1_BLOCK1_ADDRESS) && ((Address <= (IntFlashLdd1_BLOCK1_ADDRESS + IntFlashLdd1_BLOCK1_SIZE))))) {
      return ERR_PARAM_SIZE;
    }
  }
  if (DevDataPtr->CurrentOperationStatus > LDD_FLASH_IDLE) {
    return ERR_BUSY;
  }
  return ERR_OK;
}

/*
** ===================================================================
**     Method      :  IntFlashLdd1_Init (component FLASH_LDD)
*/
/*!
**     @brief
**         Initializes the device. Allocates memory for the device data
**         structure, allocates interrupt vectors and sets interrupt
**         priority, sets pin routing, sets timing, etc. If the "Enable
**         in init. code" property is set to "yes" ([Enabled in init.
**         code]) value then the device is also enabled(see the
**         description of the Enable() method). In this case the
**         Enable() method is not necessary and needn't to be generated.
**         This method can be called only once. Before the second call
**         of Init() the Deinit() must be called first.
**     @param
**         UserDataPtr     - Pointer to the user or
**                           RTOS specific data. This pointer will be
**                           passed as an event or callback parameter.
**     @return
**                         - Device data structure pointer.
*/
/* ===================================================================*/
LDD_TDeviceData* IntFlashLdd1_Init(LDD_TUserData *UserDataPtr)
{
  IntFlashLdd1_TDeviceData *DevDataPtr;

  /* Allocate FLASH_LDD device structure */
  /* {Default RTOS Adapter} Driver memory allocation: Dynamic allocation is simulated by a pointer to the static object */
  DevDataPtr = &DevDataPtr__DEFAULT_RTOS_ALLOC;
  DevDataPtr->UserDataPtr = UserDataPtr; /* Store the user data */
  /* Allocate interrupt vector(s) */
  /* {Default RTOS Adapter} Set interrupt vector: IVT is static, ISR parameter is passed by the global variable */
  INT_FTMRH__DEFAULT_RTOS_ISRPARAM = DevDataPtr;
  /* Registration of the device structure */
  PE_LDD_RegisterDeviceStructure(PE_LDD_COMPONENT_IntFlashLdd1_ID,DevDataPtr);
  DevDataPtr->CurrentOperationStatus = LDD_FLASH_IDLE; /* Initialization of the Current operation status variable */
  DevDataPtr->CurrentOperation = LDD_FLASH_NO_OPERATION; /* Initialization of the Current operation type item */
  DevDataPtr->CurrentErrorFlags = 0U;  /* Initialization of the Current error flags item */
  #if defined(SIM_PDD_CLOCK_GATE_FTMRH)
  SIM_PDD_SetClockGate(SIM_BASE_PTR, SIM_PDD_CLOCK_GATE_FTMRH, PDD_ENABLE);
  #endif
  /* FTMRH_FCLKDIV: FDIVLD=0,FDIVLCK=0,FDIV=0x13 */
  FTMRH_FCLKDIV = FTMRH_FCLKDIV_FDIV(0x13); /* Set clock divider */
  /* NVIC_IPR1: PRI_5=0x80 */
  NVIC_IPR1 = (uint32_t)((NVIC_IPR1 & (uint32_t)~(uint32_t)(
               NVIC_IP_PRI_5(0x7F)
              )) | (uint32_t)(
               NVIC_IP_PRI_5(0x80)
              ));
  /* NVIC_ISER: SETENA|=0x20 */
  NVIC_ISER |= NVIC_ISER_SETENA(0x20);
  return DevDataPtr;
}

/*
** ===================================================================
**     Method      :  IntFlashLdd1_Write (component FLASH_LDD)
*/
/*!
**     @brief
**         This method sets up a flash memory write operation. The
**         operation itself is performing by defined batches (property
**         [Write batch size]) by periodical calling the component’s
**         Main method in the user application (higher level OS service)
**         or by the component’s ISR, if an component’s interrupt
**         service is enabled.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @param
**         FromPtr         - Pointer to data to be written to
**                           the flash memory.
**     @param
**         ToAddress       - Address to the flash memory
**                           the input data would be written to.
**     @param
**         Size            - Size of the input data (in bytes) to be
**                           written to the flash memory.
**     @return
**                         - Error code
**                           ERR_OK - OK
**                           ERR_DISABLED - Component is disabled
**                           ERR_SPEED - This device does not work in
**                           the active clock configuration
**                           ERR_BUSY - Some flash memory operation is
**                           already in progress 
**                           ERR_PARAM_ADDRESS - Desired flash memory
**                           area is out of allowed range
**                           ERR_NOTAVAIL - When Safe launch and wait
**                           mode is enabled (property Safe launch and
**                           wait) and safe routine location is defined
**                           in runtime (property Safe routine location)
**                           and the safe routine location has not been
**                           specified yet (the SetSafeRoutineLocation
**                           method has not been used to define the
**                           location the safe routine will be copied to).
*/
/* ===================================================================*/
LDD_TError IntFlashLdd1_Write(LDD_TDeviceData *DeviceDataPtr, LDD_TData *FromPtr, LDD_FLASH_TAddress ToAddress, LDD_FLASH_TDataSize Size)
{
  IntFlashLdd1_TDeviceDataPtr DevDataPtr = (IntFlashLdd1_TDeviceDataPtr)DeviceDataPtr;
  LDD_TError Result;
  
  Result = CheckStateAndRange(DevDataPtr, ToAddress, Size);
  if (Result != ERR_OK) {
    return Result;
  }
  if (ToAddress >= IntFlashLdd1_EEPROM_ADDRESS) {
    /* EEPROM memory is addressed */
    FTMRH_PDD_SetCommand(FTMRH_BASE_PTR, FTMRH_PDD_CMD_PROGRAM_EEPROM);
  } else {
    /* FLASH memory is addressed */
    FTMRH_PDD_SetCommand(FTMRH_BASE_PTR, FTMRH_PDD_CMD_PROGRAM_FLASH);
  }
  DevDataPtr->CurrentOperation = LDD_FLASH_WRITE;
  DevDataPtr->CurrentOperationStatus = LDD_FLASH_START;
  DevDataPtr->CurrentUserAddress = (uint32_t)FromPtr;
  DevDataPtr->CurrentFlashAddress = ToAddress;
  DevDataPtr->CurrentDataSize = Size;
  FTMRH_PDD_EnableCommandCompleteInterrupt(FTMRH_BASE_PTR); /* Enable the Command complete interrupt */
  return ERR_OK;
}

/*
** ===================================================================
**     Method      :  IntFlashLdd1_GetOperationStatus (component FLASH_LDD)
*/
/*!
**     @brief
**         Returns a status of current (last) flash memory operation.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @return
**                         - Current flash memory operation status. See
**                           the LDD_FLASH_TOperationStatus type's
**                           description for details.
*/
/* ===================================================================*/
LDD_FLASH_TOperationStatus IntFlashLdd1_GetOperationStatus(LDD_TDeviceData *DeviceDataPtr)
{
  return ((IntFlashLdd1_TDeviceDataPtr)(DeviceDataPtr))->CurrentOperationStatus; /* Return current operation status */
}

/*
** ===================================================================
**     Method      :  IntFlashLdd1_GetError (component FLASH_LDD)
*/
/*!
**     @brief
**         Returns an error state of a current (or last) flash
**         operation. 
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @param
**         OperationStatus - Pointer to an
**                           output structure with the error status
**                           details. See the LDD_FLASH_TErrorStatus
**                           type's description for details.
*/
/* ===================================================================*/
void IntFlashLdd1_GetError(LDD_TDeviceData *DeviceDataPtr, LDD_FLASH_TErrorStatus *OperationStatus)
{
  IntFlashLdd1_TDeviceDataPtr DevDataPtr = (IntFlashLdd1_TDeviceDataPtr)DeviceDataPtr; /* Auxiliary variable - pointer to an internal state structure */

  /* Copy of information from internal status structure to the output error status structure */
  /* {Default RTOS Adapter} Critical section begin, general PE function is used */
  EnterCritical();
  OperationStatus->CurrentOperation = DevDataPtr->CurrentOperation; /* Copy the Current operation type to the output structure */
  /*
  OperationStatus->CurrentCommand = DevDataPtr->CurrentCommand;
  */
  OperationStatus->CurrentErrorFlags = DevDataPtr->CurrentErrorFlags; /* Copy the Current error flags to the output structure */
  OperationStatus->CurrentAddress = DevDataPtr->CurrentFlashAddress; /* Copy the Current flash address to the output structure */
  OperationStatus->CurrentDataPtr = (LDD_TData *)DevDataPtr->CurrentUserAddress; /* Copy the Current input/output data pointer to the output structure */
  OperationStatus->CurrentDataSize = DevDataPtr->CurrentDataSize; /* Copy the Current input/output data size to the output structure */
  /* {Default RTOS Adapter} Critical section end, general PE function is used */
  ExitCritical();
}

/*
** ===================================================================
**     Method      :  IntFlashLdd1_CommandCompleteInterrupt (component FLASH_LDD)
**
**     Description :
**         Command complete interrupt service routine.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(IntFlashLdd1_CommandCompleteInterrupt)
{
  /* {Default RTOS Adapter} ISR parameter is passed through the global variable */
  IntFlashLdd1_TDeviceDataPtr DevDataPtr = INT_FTMRH__DEFAULT_RTOS_ISRPARAM;
  uint32 Index;
  uint32_t j;
  uint32_t AlignedFlashAddress;
  uint8_t WrittenData[4];
  LDD_FLASH_TSafeRoutine SaveRoutineStackSpace;
  LDD_FLASH_TSafeRoutinePtr SafeRoutinePtr;
  uint8_t CurrentFlags;
  
  if (DevDataPtr->CurrentOperationStatus == LDD_FLASH_START) {
    /* First run of current operation */
    FTMRH_PDD_ClearFlags(FTMRH_BASE_PTR, FTMRH_PDD_ACCESS_ERROR_FLAG | FTMRH_PDD_PROTECTION_VIOLATION_FLAG);
    CurrentFlags = 0U;
    DevDataPtr->CurrentErrorFlags = 0U;
    DevDataPtr->CurrentOperationStatus = LDD_FLASH_RUNNING;
  } else {
    /* After HW command is done HW flags must be checked */
    CurrentFlags = DevDataPtr->CurrentErrorFlags | FTMRH_PDD_GetFlags(FTMRH_BASE_PTR);
  }
  if (CurrentFlags != 0U) {
    /* Command error detected */
    DevDataPtr->CurrentOperationStatus = LDD_FLASH_FAILED;
    FTMRH_PDD_DisableCommandCompleteInterrupt(FTMRH_BASE_PTR); /* Disable the Command complete interrupt */
    IntFlashLdd1_OnError(DevDataPtr->UserDataPtr);
    return;
  } else if ((int32_t)DevDataPtr->CurrentDataSize <= 0) {
    /* Command done */
    DevDataPtr->CurrentOperationStatus = LDD_FLASH_IDLE;
    FTMRH_PDD_DisableCommandCompleteInterrupt(FTMRH_BASE_PTR); /* Disable the Command complete interrupt */
    IntFlashLdd1_OnOperationComplete(DevDataPtr->UserDataPtr);
  } else {
    /* Command in progress */
    switch (DevDataPtr->CurrentOperation) {
      case LDD_FLASH_WRITE:
        Index = 2U;
        if (DevDataPtr->CurrentFlashAddress >= IntFlashLdd1_EEPROM_ADDRESS) {
          /* EEPROM memory is addressed */
          FTMRH_PDD_SetAddress(FTMRH_BASE_PTR, DevDataPtr->CurrentFlashAddress);
          while ((DevDataPtr->CurrentDataSize) && (Index <= 5U)) {
            if ((*(uint8_t*)DevDataPtr->CurrentFlashAddress ^ *(uint8_t*)DevDataPtr->CurrentUserAddress) & *(uint8_t*)DevDataPtr->CurrentUserAddress) {
              /* Only erase operation can change bits from 0 to 1 value */
              DevDataPtr->CurrentErrorFlags |= LDD_FLASH_MULTIPLE_WRITE_ERROR;
              return;
            }
            FTMRH_PDD_SetProgrammedByte(FTMRH_BASE_PTR, Index++, *(uint8_t*)DevDataPtr->CurrentUserAddress++);
            DevDataPtr->CurrentFlashAddress++;
            DevDataPtr->CurrentDataSize--;
          }
        } else {
          /* FLASH memory is addressed */
          FTMRH_PDD_SetAddress(FTMRH_BASE_PTR, DevDataPtr->CurrentFlashAddress & ~(uint32_t)IntFlashLdd1_FLASH_WRITABLE_UNIT_MASK);
          while ((DevDataPtr->CurrentDataSize) && (Index <= 5U)) {
            AlignedFlashAddress = DevDataPtr->CurrentFlashAddress & ~(uint32_t)IntFlashLdd1_FLASH_WRITABLE_UNIT_MASK;
            for (j=0x00U; j<=0x03U; j++) {
              if ((AlignedFlashAddress < DevDataPtr->CurrentFlashAddress) || (DevDataPtr->CurrentDataSize == 0x00U)) {
                WrittenData[j] = *(uint8_t*)AlignedFlashAddress++;
              } else {
                WrittenData[j] = *(uint8_t*)DevDataPtr->CurrentUserAddress++;
                DevDataPtr->CurrentDataSize--;
              }
            }
            AlignedFlashAddress = DevDataPtr->CurrentFlashAddress & ~(uint32_t)IntFlashLdd1_FLASH_WRITABLE_UNIT_MASK;
            if ((*(uint32_t*)AlignedFlashAddress ^ *(uint32_t*)(void*)WrittenData) & *(uint32_t*)(void*)WrittenData) {
              /* Only erase operation can change bits from 0 to 1 value */
              DevDataPtr->CurrentErrorFlags |= LDD_FLASH_MULTIPLE_WRITE_ERROR;
              return;
            }
            DevDataPtr->CurrentFlashAddress = AlignedFlashAddress + 4U;
            FTMRH_PDD_SetProgrammedWord(FTMRH_BASE_PTR, Index++, WrittenData[1], WrittenData[0]);
            FTMRH_PDD_SetProgrammedWord(FTMRH_BASE_PTR, Index++, WrittenData[3], WrittenData[2]);
          }
        }
        break;
      default:
        DevDataPtr->CurrentDataSize = 0U;
        break;
    }
    /* The safe routine must be aligned to 16bit word */
    SafeRoutinePtr = (LDD_FLASH_TSafeRoutinePtr)(((uint32_t)&SaveRoutineStackSpace + 1U) & ~(uint32_t)1U);
    /* Copy the safe routine's code to a buffer on the stack */
    *(LDD_FLASH_TSafeRoutine *)(void *)SafeRoutinePtr = *(LDD_FLASH_TSafeRoutine *)(void *)&SafeRoutine;
    ((LDD_FLASH_TSafeRoutinePtr)((uint32_t)(SafeRoutinePtr) | 1U))(); /* Run the Safe routine */
  }
}
/*
** ===================================================================
**     Method      :  IntFlashLdd1_GetDriverState (component FLASH_LDD)
*/
/*!
**     @brief
**         This method returns the current driver status.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @return
**                         - The current driver status mask.
**                           Following status masks defined in PE_Types.
**                           h can be used to check the current driver
**                           status.
**                           PE_LDD_DRIVER_DISABLED_IN_CLOCK_CONFIGURATIO
**                           N - 1 - Driver is disabled in the current
**                           mode; 0 - Driver is enabled in the current
**                           mode.  
**                           PE_LDD_DRIVER_DISABLED_BY_USER - 1 - Driver
**                           is disabled by the user; 0 - Driver is
**                           enabled by the user.        
**                           PE_LDD_DRIVER_BUSY - 1 - Driver is the BUSY
**                           state; 0 - Driver is in the IDLE state.
*/
/* ===================================================================*/
LDD_TDriverState IntFlashLdd1_GetDriverState(LDD_TDeviceData *DeviceDataPtr)
{
  IntFlashLdd1_TDeviceDataPtr DevDataPtr = (IntFlashLdd1_TDeviceDataPtr)DeviceDataPtr;
  LDD_TDriverState DriverState = 0x00U;

  if (DevDataPtr->CurrentOperationStatus > LDD_FLASH_IDLE) {
    DriverState |= PE_LDD_DRIVER_BUSY; /* Driver is BUSY */
  }
  return DriverState;
}

/* END IntFlashLdd1. */

#ifdef __cplusplus
}  /* extern "C" */
#endif

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
