/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : IntFlashLdd1.h
**     Project     : KESCProjectMCUXpresso
**     Processor   : SKEAZN64MLH2
**     Component   : FLASH_LDD
**     Version     : Component 01.106, Driver 01.01, CPU db: 3.00.000
**     Repository  : Kinetis
**     Compiler    : GNU C Compiler
**     Date/Time   : 2020-04-16, 21:47, # CodeGen: 128
**     Abstract    :
**          This embedded component implements an access to an on-chip flash memory.
**          Using this component the flash memory could be written to, erased,
**          read from. Some other services would be provided, if they are supported
**          by hardware, e.g. changes of the flash memory protection state.
**     Settings    :
**          Component name                                 : IntFlashLdd1
**          Device                                         : FTMRH
**          Clock frequency                                : 1 MHz
**          Use user memory areas                          : no
**          Interrupt service                              : Enabled
**            Read batch size                              : Unlimited
**            Command complete interrupt                   : 
**              Interrupt                                  : INT_FTMRH
**              Interrupt priority                         : medium priority
**          Safe launch and wait                           : yes
**            Safe routine location                        : On stack
**            Interruptable wait loop                      : no
**          Initialization                                 : 
**            Enabled in init. code                        : yes
**            Auto initialization                          : no
**            Event mask                                   : 
**              OnOperationComplete                        : Enabled
**              OnError                                    : Enabled
**            CPU clock/configuration selection            : 
**              Clock configuration 0                      : This component enabled
**              Clock configuration 1                      : This component disabled
**              Clock configuration 2                      : This component disabled
**              Clock configuration 3                      : This component disabled
**              Clock configuration 4                      : This component disabled
**              Clock configuration 5                      : This component disabled
**              Clock configuration 6                      : This component disabled
**              Clock configuration 7                      : This component disabled
**     Contents    :
**         Init               - LDD_TDeviceData* IntFlashLdd1_Init(LDD_TUserData *UserDataPtr);
**         Write              - LDD_TError IntFlashLdd1_Write(LDD_TDeviceData *DeviceDataPtr, LDD_TData...
**         GetOperationStatus - LDD_FLASH_TOperationStatus IntFlashLdd1_GetOperationStatus(LDD_TDeviceData...
**         GetError           - void IntFlashLdd1_GetError(LDD_TDeviceData *DeviceDataPtr,...
**         GetDriverState     - LDD_TDriverState IntFlashLdd1_GetDriverState(LDD_TDeviceData *DeviceDataPtr);
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file IntFlashLdd1.h
** @version 01.01
** @brief
**          This embedded component implements an access to an on-chip flash memory.
**          Using this component the flash memory could be written to, erased,
**          read from. Some other services would be provided, if they are supported
**          by hardware, e.g. changes of the flash memory protection state.
*/         
/*!
**  @addtogroup IntFlashLdd1_module IntFlashLdd1 module documentation
**  @{
*/         

#ifndef __IntFlashLdd1_H
#define __IntFlashLdd1_H

/* MODULE IntFlashLdd1. */

/* Include shared modules, which are used for whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited beans */
#include "Cpu.h"


/*! Peripheral base address of a device allocated by the component. This constant can be used directly in PDD macros. */
#define IntFlashLdd1_PRPH_BASE_ADDRESS  0x40020000U
  
/* Methods configuration constants - generated for all enabled component's methods */
#define IntFlashLdd1_Init_METHOD_ENABLED /*!< Init method of the component IntFlashLdd1 is enabled (generated) */
#define IntFlashLdd1_Write_METHOD_ENABLED /*!< Write method of the component IntFlashLdd1 is enabled (generated) */
#define IntFlashLdd1_GetOperationStatus_METHOD_ENABLED /*!< GetOperationStatus method of the component IntFlashLdd1 is enabled (generated) */
#define IntFlashLdd1_GetError_METHOD_ENABLED /*!< GetError method of the component IntFlashLdd1 is enabled (generated) */
#define IntFlashLdd1_GetDriverState_METHOD_ENABLED /*!< GetDriverState method of the component IntFlashLdd1 is enabled (generated) */

/* Events configuration constants - generated for all enabled component's events */
#define IntFlashLdd1_OnOperationComplete_EVENT_ENABLED /*!< OnOperationComplete event of the component IntFlashLdd1 is enabled (generated) */
#define IntFlashLdd1_OnError_EVENT_ENABLED /*!< OnError event of the component IntFlashLdd1 is enabled (generated) */

/* Driver mode */
#define IntFlashLdd1_INTERRUPT_MODE

/* FLASH memory general parameters */
#define IntFlashLdd1_FLASH_ADDRESS                    0x00U
#define IntFlashLdd1_FLASH_SIZE                       0x00010000U
#define IntFlashLdd1_FLASH_ERASABLE_UNIT_SIZE         0x0200U
#define IntFlashLdd1_FLASH_ERASABLE_UNIT_MASK         (IntFlashLdd1_FLASH_ERASABLE_UNIT_SIZE - 1U)
#define IntFlashLdd1_FLASH_WRITABLE_UNIT_SIZE         0x04U
#define IntFlashLdd1_FLASH_WRITABLE_UNIT_MASK         (IntFlashLdd1_FLASH_WRITABLE_UNIT_SIZE - 1U)

/* EEPROM memory general parameters */
#define IntFlashLdd1_EEPROM_ADDRESS              0x10000000U
#define IntFlashLdd1_EEPROM_SIZE                 0x0100U
#define IntFlashLdd1_EEPROM_ERASABLE_UNIT_SIZE   0x02U
#define IntFlashLdd1_EEPROM_ERASABLE_UNIT_MASK   (IntFlashLdd1_EEPROM_ERASABLE_UNIT_SIZE - 1U)
#define IntFlashLdd1_EEPROM_WRITABLE_UNIT_SIZE   0x01U
#define IntFlashLdd1_EEPROM_WRITABLE_UNIT_MASK   (IntFlashLdd1_EPROM_WRITABLE_UNIT_SIZE - 1U)

/* FLASH block 0 parameters */
#define IntFlashLdd1_BLOCK0_ADDRESS              0x00LU
#define IntFlashLdd1_BLOCK0_SIZE                 0x00010000LU
#define IntFlashLdd1_BLOCK0_WRITABLE_UNIT_SIZE   0x04LU
#define IntFlashLdd1_BLOCK0_ERASABLE_UNIT_SIZE   0x0200LU

/* EEPROM block 0 parameters */
#define IntFlashLdd1_BLOCK1_ADDRESS              0x10000000LU
#define IntFlashLdd1_BLOCK1_SIZE                 0x0100LU
#define IntFlashLdd1_BLOCK1_WRITABLE_UNIT_SIZE   0x01LU
#define IntFlashLdd1_BLOCK1_ERASABLE_UNIT_SIZE   0x02LU

/*
** ===================================================================
**     Method      :  IntFlashLdd1_Init (component FLASH_LDD)
*/
/*!
**     @brief
**         Initializes the device. Allocates memory for the device data
**         structure, allocates interrupt vectors and sets interrupt
**         priority, sets pin routing, sets timing, etc. If the "Enable
**         in init. code" property is set to "yes" ([Enabled in init.
**         code]) value then the device is also enabled(see the
**         description of the Enable() method). In this case the
**         Enable() method is not necessary and needn't to be generated.
**         This method can be called only once. Before the second call
**         of Init() the Deinit() must be called first.
**     @param
**         UserDataPtr     - Pointer to the user or
**                           RTOS specific data. This pointer will be
**                           passed as an event or callback parameter.
**     @return
**                         - Device data structure pointer.
*/
/* ===================================================================*/
LDD_TDeviceData* IntFlashLdd1_Init(LDD_TUserData *UserDataPtr);

/*
** ===================================================================
**     Method      :  IntFlashLdd1_Write (component FLASH_LDD)
*/
/*!
**     @brief
**         This method sets up a flash memory write operation. The
**         operation itself is performing by defined batches (property
**         [Write batch size]) by periodical calling the component’s
**         Main method in the user application (higher level OS service)
**         or by the component’s ISR, if an component’s interrupt
**         service is enabled.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @param
**         FromPtr         - Pointer to data to be written to
**                           the flash memory.
**     @param
**         ToAddress       - Address to the flash memory
**                           the input data would be written to.
**     @param
**         Size            - Size of the input data (in bytes) to be
**                           written to the flash memory.
**     @return
**                         - Error code
**                           ERR_OK - OK
**                           ERR_DISABLED - Component is disabled
**                           ERR_SPEED - This device does not work in
**                           the active clock configuration
**                           ERR_BUSY - Some flash memory operation is
**                           already in progress 
**                           ERR_PARAM_ADDRESS - Desired flash memory
**                           area is out of allowed range
**                           ERR_NOTAVAIL - When Safe launch and wait
**                           mode is enabled (property Safe launch and
**                           wait) and safe routine location is defined
**                           in runtime (property Safe routine location)
**                           and the safe routine location has not been
**                           specified yet (the SetSafeRoutineLocation
**                           method has not been used to define the
**                           location the safe routine will be copied to).
*/
/* ===================================================================*/
LDD_TError IntFlashLdd1_Write(LDD_TDeviceData *DeviceDataPtr, LDD_TData *FromPtr, LDD_FLASH_TAddress ToAddress, LDD_FLASH_TDataSize Size);

/*
** ===================================================================
**     Method      :  IntFlashLdd1_GetOperationStatus (component FLASH_LDD)
*/
/*!
**     @brief
**         Returns a status of current (last) flash memory operation.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @return
**                         - Current flash memory operation status. See
**                           the LDD_FLASH_TOperationStatus type's
**                           description for details.
*/
/* ===================================================================*/
LDD_FLASH_TOperationStatus IntFlashLdd1_GetOperationStatus(LDD_TDeviceData *DeviceDataPtr);

/*
** ===================================================================
**     Method      :  IntFlashLdd1_GetError (component FLASH_LDD)
*/
/*!
**     @brief
**         Returns an error state of a current (or last) flash
**         operation. 
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @param
**         OperationStatus - Pointer to an
**                           output structure with the error status
**                           details. See the LDD_FLASH_TErrorStatus
**                           type's description for details.
*/
/* ===================================================================*/
void IntFlashLdd1_GetError(LDD_TDeviceData *DeviceDataPtr, LDD_FLASH_TErrorStatus *OperationStatus);

/*
** ===================================================================
**     Method      :  IntFlashLdd1_CommandCompleteInterrupt (component FLASH_LDD)
**
**     Description :
**         Command complete interrupt service routine.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
/* {Default RTOS Adapter} ISR function prototype */
PE_ISR(IntFlashLdd1_CommandCompleteInterrupt);

/*
** ===================================================================
**     Method      :  IntFlashLdd1_SetClockConfiguration (component FLASH_LDD)
**
**     Description :
**         This method changes the clock configuration. During a clock 
**         configuration change the component changes it's setting 
**         immediately upon a request.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void IntFlashLdd1_SetClockConfiguration(LDD_TDeviceData *DeviceDataPtr, LDD_TClockConfiguration ClockConfiguration);

/*
** ===================================================================
**     Method      :  IntFlashLdd1_GetDriverState (component FLASH_LDD)
*/
/*!
**     @brief
**         This method returns the current driver status.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @return
**                         - The current driver status mask.
**                           Following status masks defined in PE_Types.
**                           h can be used to check the current driver
**                           status.
**                           PE_LDD_DRIVER_DISABLED_IN_CLOCK_CONFIGURATIO
**                           N - 1 - Driver is disabled in the current
**                           mode; 0 - Driver is enabled in the current
**                           mode.  
**                           PE_LDD_DRIVER_DISABLED_BY_USER - 1 - Driver
**                           is disabled by the user; 0 - Driver is
**                           enabled by the user.        
**                           PE_LDD_DRIVER_BUSY - 1 - Driver is the BUSY
**                           state; 0 - Driver is in the IDLE state.
*/
/* ===================================================================*/
LDD_TDriverState IntFlashLdd1_GetDriverState(LDD_TDeviceData *DeviceDataPtr);

/* END IntFlashLdd1. */

#endif
/* ifndef __IntFlashLdd1_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
