/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : WDOG.h
**     Project     : KESCProjectCW
**     Processor   : SKEAZN64MLH2
**     Component   : Init_WDOG
**     Version     : Component 01.007, Driver 01.07, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2019-12-08, 19:02, # CodeGen: 0
**     Abstract    :
**          This file implements the WDOG (WDOG) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
**     Settings    :
**          Component name                                 : WDOG
**          Device                                         : WDOG
**          Settings                                       : 
**            Clock settings                               : 
**              Watchdog Configuration Time (WCT)          : 12.800 us
**              Clock select                               : Bus clock
**              Prescaler                                  : divide by 256
**              Time-out value                             : 400
**              Time-out period                            : 5.120 ms
**            Window mode settings                         : 
**              Windowing mode                             : Disabled
**              Window value                               : 0
**              Window                                     : STOPPED
**            Wait mode                                    : Enabled
**            Stop mode                                    : Enabled
**            Debug mode                                   : Disabled
**            Allow update                                 : Enabled
**          Interrupts                                     : 
**            Interrupt                                    : INT_Watchdog
**            Interrupt request                            : Disabled
**            Interrupt priority                           : 0 (Highest)
**            ISR name                                     : 
**            Watchdog interrupt                           : Disabled
**          Initialization                                 : 
**            Enable WDOG                                  : no
**            Call Init method                             : no
**     Contents    :
**         Init - void WDOG_Init(void);
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file WDOG.h
** @version 01.07
** @brief
**          This file implements the WDOG (WDOG) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
*/         
/*!
**  @addtogroup WDOG_module WDOG module documentation
**  @{
*/         

#ifndef WDOG_H_
#define WDOG_H_

/* MODULE WDOG. */

/* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"

/* Peripheral base address parameter */
#define WDOG_DEVICE WDOG_BASE_PTR


/*
** ===================================================================
**     Method      :  WDOG_Init (component Init_WDOG)
**     Description :
**         This method initializes registers of the WDOG module
**         according to the Peripheral Initialization settings.
**         Call this method in user code to initialize the module. By
**         default, the method is called by PE automatically; see "Call
**         Init method" property of the component for more details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void WDOG_Init(void);


/* END WDOG. */
#endif /* #ifndef __WDOG_H_ */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
